---
title: "DS 4002 EDA"
author: "Ani Ponugoti"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(scales)
bins_df <- read.csv("bins_df.csv")
str_len_bins_df <- read.csv("str_len_bins_df.csv")
```

```{r}
level_order <- c("Less than 100", "100 to 199", "200 to 299", "300 to 399", "400 to 499", "500 to 999", "1,000 or more")

ggplot(str_len_bins_df, aes(x=bin, y=num, fill=lang)) + 
  geom_bar(position="dodge", stat="identity") + 
  scale_x_discrete(limits=level_order) + 
  scale_y_continuous(label=comma) +
  labs(x="String Length (characters)", y="Count", title="String Length Frequency by Language") + 
  theme_minimal() + theme(plot.title = element_text(hjust = 0.5), 
                        panel.grid.major.x = element_blank()) + 
  scale_fill_manual(name="Language", values=c("#BF0A30", "#0055A4"), labels=c("English", "French")) 
```

```{r}
en_fr_df <- read.csv("en_fr_combined.csv")
```

```{r}
str_lens_df <- read.csv("str_lens_df.csv")
```


```{r}
# str_lens <- read.csv("str_lens.csv")
```

```{r}
ggplot(str_lens_df, aes(x=lang, y=str_len, fill=lang)) + geom_boxplot(outlier.shape=NA) + 
  scale_y_continuous(limits=c(0, 400)) + 
  scale_x_discrete(labels=c("English", "French")) + 
  labs(x="Language", y="String Length (characters)", title="Distribution of String Length by Language") + theme_minimal() + 
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major.x = element_blank()) + 
  scale_fill_manual(values=c("#BF0A30", "#0055A4"), guide="none")
```

